/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouter_reclamation (void)
{
  GtkWidget *ajouter_reclamation;
  GtkWidget *fixed1;
  GtkWidget *label2;
  GtkWidget *idajout;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *reclam_ajout;
  GtkWidget *label7;
  GtkObject *h_ajout_adj;
  GtkWidget *h_ajout;
  GtkWidget *label8;
  GtkObject *m_ajout_adj;
  GtkWidget *m_ajout;
  GtkWidget *afficher;
  GtkWidget *ajouter;
  GtkWidget *annuler;
  GtkWidget *bv_ajout;
  GtkWidget *type_ajout;
  GtkWidget *liste_ajout;
  GtkWidget *alerte;

  ajouter_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_reclamation), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouter_reclamation), fixed1);

  label2 = gtk_label_new (_("id observateur"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 24);
  gtk_widget_set_size_request (label2, 41, 17);

  idajout = gtk_entry_new ();
  gtk_widget_show (idajout);
  gtk_fixed_put (GTK_FIXED (fixed1), idajout, 72, 16);
  gtk_widget_set_size_request (idajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idajout), 8226);

  label3 = gtk_label_new (_("type de reclamation"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 24, 64);
  gtk_widget_set_size_request (label3, 41, 17);

  label4 = gtk_label_new (_("liste electorale"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 32, 112);
  gtk_widget_set_size_request (label4, 41, 17);

  label5 = gtk_label_new (_("bureau de vote"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 16, 152);
  gtk_widget_set_size_request (label5, 41, 17);

  label6 = gtk_label_new (_("reclamation:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 16, 192);
  gtk_widget_set_size_request (label6, 41, 17);

  reclam_ajout = gtk_entry_new ();
  gtk_widget_show (reclam_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), reclam_ajout, 72, 192);
  gtk_widget_set_size_request (reclam_ajout, 264, 104);
  gtk_entry_set_invisible_char (GTK_ENTRY (reclam_ajout), 8226);

  label7 = gtk_label_new (_("heure"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 328, 32);
  gtk_widget_set_size_request (label7, 41, 17);

  h_ajout_adj = gtk_adjustment_new (1, 0, 23, 1, 10, 10);
  h_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (h_ajout_adj), 1, 0);
  gtk_widget_show (h_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), h_ajout, 376, 24);
  gtk_widget_set_size_request (h_ajout, 60, 27);

  label8 = gtk_label_new (_("minute"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 448, 32);
  gtk_widget_set_size_request (label8, 41, 17);

  m_ajout_adj = gtk_adjustment_new (1, 0, 60, 1, 10, 10);
  m_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (m_ajout_adj), 1, 0);
  gtk_widget_show (m_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), m_ajout, 496, 24);
  gtk_widget_set_size_request (m_ajout, 60, 27);

  afficher = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 368, 320);
  gtk_widget_set_size_request (afficher, 66, 29);

  ajouter = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 440, 320);
  gtk_widget_set_size_request (ajouter, 66, 29);

  annuler = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), annuler, 512, 320);
  gtk_widget_set_size_request (annuler, 66, 29);

  bv_ajout = gtk_combo_box_entry_new_text ();
  gtk_widget_show (bv_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), bv_ajout, 88, 152);
  gtk_widget_set_size_request (bv_ajout, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (bv_ajout), _("bv1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (bv_ajout), _("bv2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (bv_ajout), _("bv3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (bv_ajout), _("bv4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (bv_ajout), _("bv5"));

  type_ajout = gtk_combo_box_entry_new_text ();
  gtk_widget_show (type_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), type_ajout, 80, 56);
  gtk_widget_set_size_request (type_ajout, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_ajout), _("le respect des droits"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_ajout), _("l'objectivite du couverture de la part du media"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_ajout), _("l'organisation d'elections"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (type_ajout), _("le transparence"));

  liste_ajout = gtk_combo_box_entry_new_text ();
  gtk_widget_show (liste_ajout);
  gtk_fixed_put (GTK_FIXED (fixed1), liste_ajout, 88, 104);
  gtk_widget_set_size_request (liste_ajout, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (liste_ajout), _("liste1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (liste_ajout), _("liste2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (liste_ajout), _("liste3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (liste_ajout), _("liste4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (liste_ajout), _("liste5"));

  label8 = gtk_check_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 48, 320);
  gtk_widget_set_size_request (label8, 118, 24);

  alerte = gtk_label_new ("");
  gtk_widget_show (alerte);
  gtk_fixed_put (GTK_FIXED (fixed1), alerte, 184, 320);
  gtk_widget_set_size_request (alerte, 160, 32);

  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) label8, "toggled",
                    G_CALLBACK (on_label8_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_reclamation, ajouter_reclamation, "ajouter_reclamation");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, idajout, "idajout");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, reclam_ajout, "reclam_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, h_ajout, "h_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, m_ajout, "m_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, bv_ajout, "bv_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, type_ajout, "type_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, liste_ajout, "liste_ajout");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, alerte, "alerte");

  return ajouter_reclamation;
}

GtkWidget*
create_affichage (void)
{
  GtkWidget *affichage;
  GtkWidget *fixed2;
  GtkWidget *list_aff;
  GtkWidget *annuleraff;
  GtkWidget *actualiseraff;
  GtkWidget *retouraff;

  affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (affichage), fixed2);

  list_aff = gtk_tree_view_new ();
  gtk_widget_show (list_aff);
  gtk_fixed_put (GTK_FIXED (fixed2), list_aff, 8, 16);
  gtk_widget_set_size_request (list_aff, 300, 200);

  annuleraff = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (annuleraff);
  gtk_fixed_put (GTK_FIXED (fixed2), annuleraff, 200, 264);
  gtk_widget_set_size_request (annuleraff, 66, 29);

  actualiseraff = gtk_button_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (actualiseraff);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiseraff, 280, 264);
  gtk_widget_set_size_request (actualiseraff, 88, 32);

  retouraff = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (retouraff);
  gtk_fixed_put (GTK_FIXED (fixed2), retouraff, 120, 264);
  gtk_widget_set_size_request (retouraff, 66, 29);

  g_signal_connect ((gpointer) annuleraff, "clicked",
                    G_CALLBACK (on_annuleraff_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiseraff, "clicked",
                    G_CALLBACK (on_actualiseraff_clicked),
                    NULL);
  g_signal_connect ((gpointer) retouraff, "clicked",
                    G_CALLBACK (on_retouraff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage, affichage, "affichage");
  GLADE_HOOKUP_OBJECT (affichage, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (affichage, list_aff, "list_aff");
  GLADE_HOOKUP_OBJECT (affichage, annuleraff, "annuleraff");
  GLADE_HOOKUP_OBJECT (affichage, actualiseraff, "actualiseraff");
  GLADE_HOOKUP_OBJECT (affichage, retouraff, "retouraff");

  return affichage;
}

